name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev python3-dev gzip zip unzip openjdk-17-jdk ccache ffmpeg autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libgdbm-dev libsqlite3-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev tk-dev

    - name: Install Python Dependencies
      run: |
        python3.10 -m pip install --upgrade pip setuptools
        python3.10 -m pip install buildozer "cython<3.0.0"

    - name: Build APK with Buildozer
      run: |
        APP_ANDROID_ACCEPT_SDK_LICENSES=1 python3.10 -m buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk
